export const navItems = [
  { id: 'home', label: 'Ana Sayfa' },
  { id: 'shelter', label: 'Barınma' },
  { id: 'match', label: 'Yardım Eşleştir' },
  { id: 'donations', label: 'Bağış Yap' },
  { id: 'map', label: 'Afet Haritası' },
  { id: 'volunteer', label: 'Gönüllü Ol' },
  { id: 'profile', label: 'Profil' },
]

export const mobileNavItems = [
  { id: 'home', label: 'Ana Sayfa', short: 'Ana' },
  { id: 'map', label: 'Harita', short: 'Harita' },
  { id: 'create', label: 'İlan Ver', short: 'İlan' },
  { id: 'donations', label: 'Bağış', short: 'Bağış' },
  { id: 'profile', label: 'Profil', short: 'Profil' },
]

export const cities = ['Gaziantep', 'Hatay', 'Kahramanmaraş', 'Adıyaman', 'Malatya', 'Şanlıurfa']

export const disasterZones = [
  {
    city: 'Hatay',
    district: 'Antakya',
    level: 'Yüksek',
    status: 'Aktif afet bölgesi',
    needs: ['sıcak yemek', 'barınma', 'minibüs'],
    updated: '8 dk önce',
    coordination: '3 toplama merkezi aktif',
  },
  {
    city: 'Adıyaman',
    district: 'Merkez',
    level: 'Orta',
    status: 'İzleniyor',
    needs: ['su', 'hijyen', 'depo'],
    updated: '14 dk önce',
    coordination: '2 gönüllü ekibi sahada',
  },
  {
    city: 'Malatya',
    district: 'Battalgazi',
    level: 'Orta',
    status: 'Aktif destek',
    needs: ['bebek bezi', 'mama', 'battaniye'],
    updated: '22 dk önce',
    coordination: '1 lojistik noktası açık',
  },
]

export const urgentNeeds = [
  {
    id: 1,
    location: 'Hatay / Antakya',
    need: '20 kişilik sıcak yemek ihtiyacı',
    type: 'Gıda',
    level: 'Acil',
    people: 20,
    updated: '5 dk önce',
    status: 'Acil',
  },
  {
    id: 2,
    location: 'Adıyaman Merkez',
    need: '2 minibüs gerekiyor',
    type: 'Araç',
    level: 'Yüksek',
    people: 40,
    updated: '11 dk önce',
    status: 'Yardım bekliyor',
  },
  {
    id: 3,
    location: 'Kahramanmaraş',
    need: '10 aile için kalacak yer aranıyor',
    type: 'Barınma',
    level: 'Acil',
    people: 34,
    updated: '18 dk önce',
    status: 'Yardım bekliyor',
  },
  {
    id: 4,
    location: 'Malatya',
    need: 'Bebek bezi ve mama ihtiyacı var',
    type: 'Bebek',
    level: 'Orta',
    people: 12,
    updated: '24 dk önce',
    status: 'Yardım yolda',
  },
  {
    id: 5,
    location: 'Şanlıurfa / Haliliye',
    need: 'Depoda hijyen kolisi ayrıştırma desteği',
    type: 'Gönüllü',
    level: 'Orta',
    people: 8,
    updated: '31 dk önce',
    status: 'Yardım bekliyor',
  },
]

export const shelterListings = [
  {
    id: 1,
    city: 'Gaziantep',
    district: 'Şahinbey',
    capacity: 3,
    family: true,
    children: true,
    gender: 'Çocuklu aile / karma',
    duration: '7 gün',
    pets: false,
    disabled: false,
    transport: true,
    verified: true,
    type: 'Oda',
    amenities: ['Isınma', 'Banyo', 'Mutfak'],
    note: 'Gaziantep / Şahinbey’de 3 kişilik aile için uygun bir oda. Çocuklu aile kabul edilir.',
    hostScore: 4.8,
  },
  {
    id: 2,
    city: 'Hatay',
    district: 'Dörtyol',
    capacity: 5,
    family: true,
    children: true,
    gender: 'Aile öncelikli',
    duration: '10 gün',
    pets: true,
    disabled: true,
    transport: true,
    verified: true,
    type: 'Tüm ev',
    amenities: ['Isınma', 'Banyo', 'Mutfak', 'Ulaşım'],
    note: 'Zemin kat, engelli birey için uygun. Evcil hayvan kabul edilir.',
    hostScore: 4.9,
  },
  {
    id: 3,
    city: 'Malatya',
    district: 'Battalgazi',
    capacity: 2,
    family: false,
    children: false,
    gender: 'Kadın',
    duration: '5 gün',
    pets: false,
    disabled: false,
    transport: false,
    verified: false,
    type: 'Misafir odası',
    amenities: ['Isınma', 'Banyo'],
    note: 'Kadın afetzedeler için güvenli misafir odası. Admin onayı bekliyor.',
    hostScore: 4.3,
  },
  {
    id: 4,
    city: 'Şanlıurfa',
    district: 'Eyyübiye',
    capacity: 4,
    family: true,
    children: true,
    gender: 'Aile / çocuklu aile',
    duration: '14 gün',
    pets: true,
    disabled: false,
    transport: true,
    verified: true,
    type: 'Apart',
    amenities: ['Isınma', 'Banyo', 'Mutfak', 'Ulaşım'],
    note: 'Toplu taşıma yakını, mutfak ortak kullanılabilir.',
    hostScore: 4.7,
  },
]

export const aidListings = [
  {
    id: 1,
    type: 'Aracım var, yardım taşıyabilirim',
    location: 'Gaziantep / Şehitkamil',
    offered: 'Minibüs ve sürücü',
    needed: 'Kuru gıda veya hijyen kolisi',
    availability: 'Bugün 18.00',
    capacity: '1 ton',
    urgency: 'Yüksek',
    status: 'Bekliyor',
  },
  {
    id: 2,
    type: 'Erzağım var, araç arıyorum',
    location: 'Gaziantep / Merkez',
    offered: '50 koli kuru gıda',
    needed: 'Hatay yönüne araç desteği',
    availability: 'Bugün',
    capacity: '50 koli',
    urgency: 'Acil',
    status: 'Bekliyor',
  },
  {
    id: 3,
    type: 'Depom var, yardımlar burada toplanabilir',
    location: 'Adıyaman / Merkez',
    offered: '200 m2 kapalı depo',
    needed: 'Paketleme gönüllüleri',
    availability: '24 saat',
    capacity: '400 koli',
    urgency: 'Orta',
    status: 'Eşleşti',
  },
  {
    id: 4,
    type: 'Gönüllüyüm, dağıtıma katılabilirim',
    location: 'Hatay / Antakya',
    offered: '4 kişilik dağıtım ekibi',
    needed: 'Araç ve rota bilgisi',
    availability: 'Yarın 09.00',
    capacity: '4 gönüllü',
    urgency: 'Yüksek',
    status: 'Yardım yolda',
  },
  {
    id: 5,
    type: 'Yardım bölgesinde ihtiyaç bildiriyorum',
    location: 'Malatya / Battalgazi',
    offered: 'Teslim alacak koordinatör mevcut',
    needed: 'Bebek maması, bez, battaniye',
    availability: 'Acil',
    capacity: '15 aile',
    urgency: 'Acil',
    status: 'Bekliyor',
  },
  {
    id: 6,
    type: 'Yardım götürmek istiyorum ama ekip arıyorum',
    location: 'Kahramanmaraş / Onikişubat',
    offered: 'Araç ve yakıt desteği',
    needed: '2 gönüllü, paketleme desteği',
    availability: 'Bu akşam',
    capacity: '750 kg',
    urgency: 'Orta',
    status: 'Tamamlandı',
  },
]

export const donationPackages = [
  {
    id: 1,
    name: 'Gıda Kolisi',
    items: ['Kuru bakliyat', 'konserve', 'çay', 'makarna'],
    price: '650 TL',
    supports: '4 kişilik aileye 3 gün',
  },
  {
    id: 2,
    name: 'Hijyen Paketi',
    items: ['Sabun', 'şampuan', 'dezenfektan', 'ıslak mendil'],
    price: '420 TL',
    supports: '5 kişiye temel hijyen',
  },
  {
    id: 3,
    name: 'Bebek Destek Paketi',
    items: ['Mama', 'bebek bezi', 'ıslak mendil', 'pişik kremi'],
    price: '780 TL',
    supports: '1 bebeğe 1 hafta',
  },
  {
    id: 4,
    name: 'Kadın Hijyen Paketi',
    items: ['Ped', 'iç çamaşırı', 'hijyen mendili', 'sabun'],
    price: '360 TL',
    supports: '3 kadına destek',
  },
  {
    id: 5,
    name: 'Kış Paketi',
    items: ['Mont', 'çorap', 'bere', 'termal içlik'],
    price: '1.250 TL',
    supports: '1 kişiye sıcak kalma desteği',
  },
  {
    id: 6,
    name: 'Battaniye Paketi',
    items: ['2 battaniye', 'polar örtü', 'uyku matı'],
    price: '540 TL',
    supports: '2 kişiye gece desteği',
  },
  {
    id: 7,
    name: 'Su Desteği',
    items: ['120 adet 0.5L su', 'taşıma kolisi'],
    price: '300 TL',
    supports: '30 kişiye günlük su',
  },
  {
    id: 8,
    name: 'Evcil Hayvan Mama Paketi',
    items: ['Kedi maması', 'köpek maması', 'su kabı'],
    price: '480 TL',
    supports: '10 hayvana mama',
  },
]

export const mapPoints = [
  {
    id: 1,
    title: 'Antakya sıcak yemek noktası',
    type: 'Acil ihtiyaç',
    location: 'Hatay / Antakya',
    detail: '20 kişilik sıcak yemek bekleniyor',
    color: '#DC2626',
    x: 62,
    y: 36,
  },
  {
    id: 2,
    title: 'Şahinbey barınma ilanı',
    type: 'Barınma',
    location: 'Gaziantep / Şahinbey',
    detail: '3 kişilik oda doğrulandı',
    color: '#2563EB',
    x: 39,
    y: 54,
  },
  {
    id: 3,
    title: 'Haliliye yardım merkezi',
    type: 'Yardım noktası',
    location: 'Şanlıurfa / Haliliye',
    detail: 'Hijyen ve gıda kabul noktası',
    color: '#22C55E',
    x: 73,
    y: 62,
  },
  {
    id: 4,
    title: 'Minibüs yolda',
    type: 'Yardım yolda',
    location: 'Gaziantep - Hatay',
    detail: '1 ton kuru gıda taşıyor',
    color: '#F59E0B',
    x: 50,
    y: 44,
  },
  {
    id: 5,
    title: 'Adıyaman depo alanı',
    type: 'Depo / lojistik',
    location: 'Adıyaman / Merkez',
    detail: '200 m2 kapalı depo',
    color: '#7C3AED',
    x: 57,
    y: 19,
  },
  {
    id: 6,
    title: 'Güvenli toplanma alanı',
    type: 'Güvenli bölge',
    location: 'Malatya / Battalgazi',
    detail: 'Mobil sağlık ve çadır alanı',
    color: '#16A34A',
    x: 31,
    y: 26,
  },
]

export const volunteerTasks = [
  {
    id: 1,
    title: 'Erzak paketleme',
    location: 'Gaziantep / Şehitkamil',
    time: 'Bugün 16.00 - 20.00',
    people: 12,
    description: 'Gıda kolileri aile sayısına göre ayrıştırılacak.',
  },
  {
    id: 2,
    title: 'Yardım dağıtımı',
    location: 'Hatay / Antakya',
    time: 'Yarın 09.00',
    people: 8,
    description: 'Koordinatör eşliğinde mahalle bazlı dağıtım yapılacak.',
  },
  {
    id: 3,
    title: 'Araçla taşıma',
    location: 'Adıyaman / Merkez',
    time: 'Bugün 18.00',
    people: 4,
    description: 'Minibüs ve kamyonet sahipleri için kısa mesafe taşıma.',
  },
  {
    id: 4,
    title: 'Depo düzenleme',
    location: 'Şanlıurfa / Haliliye',
    time: 'Her gün 10.00',
    people: 10,
    description: 'Koliler içerik ve son kullanma tarihine göre etiketlenecek.',
  },
  {
    id: 5,
    title: 'Barınma koordinasyonu',
    location: 'Kahramanmaraş / Merkez',
    time: 'Bugün 14.00',
    people: 6,
    description: 'Kalacak yer ilanları telefon doğrulamasıyla kontrol edilecek.',
  },
  {
    id: 6,
    title: 'Yaşlı ve engelli bireylere destek',
    location: 'Malatya / Battalgazi',
    time: 'Yarın 11.00',
    people: 5,
    description: 'İlaç, ulaşım ve refakat ihtiyacı olan kişiler ziyaret edilecek.',
  },
]

export const profileData = {
  name: 'Elif Kaya',
  phone: 'Doğrulandı',
  identity: 'Kimlik doğrulaması tamamlandı',
  score: 96,
  badges: [
    'Doğrulanmış Gönüllü',
    'İlk Yardımını Yaptı',
    'Barınma Desteği Sağladı',
    'Araç Desteği Sağladı',
    '5 Yardıma Katıldı',
    'Güvenilir Destekçi',
  ],
  listings: ['Gaziantep / Şahinbey barınma ilanı', 'Minibüs ile Hatay taşıma desteği'],
  tasks: ['Erzak paketleme', 'Barınma koordinasyonu'],
  donations: ['Gıda Kolisi', 'Bebek Destek Paketi'],
  history: ['2 aileye barınma sağlandı', '1 ton kuru gıda Hatay’a ulaştı', '3 gönüllü görev tamamlandı'],
}

export const adminData = {
  pendingListings: [
    { id: 1, title: 'Malatya misafir odası', owner: 'S. Demir', type: 'Barınma', status: 'Admin onayı bekliyor' },
    { id: 2, title: 'Adıyaman depo ilanı', owner: 'Koop. 27', type: 'Depo', status: 'Kurum onayı bekliyor' },
    { id: 3, title: 'Kahramanmaraş acil ihtiyaç', owner: 'Saha ekibi', type: 'İhtiyaç', status: 'Doğrulama bekliyor' },
  ],
  reports: [
    { id: 1, title: 'Tekrarlı barınma ilanı', reason: 'Adres uyuşmuyor', priority: 'Yüksek' },
    { id: 2, title: 'Sahte bağış yönlendirmesi', reason: 'Harici IBAN paylaşımı', priority: 'Acil' },
  ],
  donations: [
    { id: 1, package: 'Gıda Kolisi', status: 'Araca yüklendi', donor: 'Anonim' },
    { id: 2, package: 'Hijyen Paketi', status: 'Paket hazırlanıyor', donor: 'M. Yılmaz' },
    { id: 3, package: 'Kış Paketi', status: 'Teslim edildi', donor: 'A. Öz' },
  ],
}
